### ISSUE TITLE
Labels (bounding boxes) for object detection task

### ISSUE THREAD

**Issue by FlorentF9** [DearCaat/CQU-BPDD#2]
In your paper "Deep Domain Adaptation for Pavement Crack Detection", you are doing object detection on CQU-BPDD, however it seems like you are only evaluating the classification task.
Do you have any instance-level bounding box annotations available for this dataset?
Thank you

**Comment by DearCaat** [comment]
Actually, I am not the author of this paper. Because CQU-BPDD does not require complicated bounding box annotations, it can expand its scale. Therefore, CQU-BPDD can make a breakthrough in Pavement Distress Classification tasks. As for the bounding box annotation information used in this article, I guess the author manually annotated some of them. I suggest contacting the first author or corresponding author of this paper directly.
